FROM node:22-alpine AS builder
WORKDIR /app

COPY .env /.env

# Copy manifests
COPY package*.json ./
COPY mongodb/package*.json ./mongodb/
COPY bot/package*.json ./bot/

RUN npm install

# Copy code
COPY mongodb ./mongodb
COPY bot ./bot

# Final image
FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/bot ./
COPY --from=builder /app/node_modules ./node_modules
ENV NODE_ENV=production
CMD ["npm", "run", "start"]